-- SQL Schema for DailyIntan Supabase

-- 1. Create history table
CREATE TABLE IF NOT EXISTS public.history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('show', 'event')),
  name TEXT NOT NULL,
  venue TEXT NOT NULL
);

-- 2. Create members table
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  team TEXT NOT NULL,
  gen TEXT NOT NULL,
  role TEXT NOT NULL,
  avatar TEXT,
  "lastUpdate" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create milestones table
CREATE TABLE IF NOT EXISTS public.milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon TEXT,
  title TEXT NOT NULL,
  val TEXT NOT NULL,
  sub TEXT NOT NULL
);

-- Allow anonymous read access
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.milestones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on history" ON public.history FOR SELECT USING (true);
CREATE POLICY "Allow public read access on members" ON public.members FOR SELECT USING (true);
CREATE POLICY "Allow public read access on milestones" ON public.milestones FOR SELECT USING (true);
